//! CREAR UN OBJETO 
const libro1 = {

    libro:"PESIMISMO. ÉTICA Y FELICIDAD",
    Autor: "Eduard Von Hartmann",
    year:"1998",

};

const libro2 = {

    libro:"CRIMEN Y CASTIGO",
    Autor: "Fiódor Dostoyevski",
    year:"1866",

};

const libro3 = {

    libro:"ORGULLO Y PERJUICIO   ",
    Autor: "Jane Austen",
    year:"1813",

};


const biblioteca = {

    libro1,
    libro2,
    libro3,

}

console.log(biblioteca)